// frontends/react/src/components/navigation/navigation.tsx
import React from "react";

import { NavigationButton } from ".";

export const Navigation: React.FC = () => {
	return (
		<nav id="nav" className="flex flex-row justify-center mb-10">
			<NavigationButton href="/" label="ABOUT" />
			<NavigationButton href="/articles" label="ARTICLES" />
		</nav>
	);
};

// frontends/svelte/src/lib/components/Navigation.svelte
<script>
	import NavigationButton from './NavigationButton.svelte';
</script>

<nav id="nav" class="mb-10 flex flex-row justify-center">
	<NavigationButton href="/" label="ABOUT" />
	<NavigationButton href="/articles" label="ARTICLES" />
	<NavigationButton href="/projects" label="PROJECTS" />
</nav>
