// frontends/react/src/components/article/articleList.tsx
import React from "react";

import { IArticle } from "src/types";
import { ArticleListItem } from "src/components/article/articleListItem";
import { Footer } from "src/components/footer";

interface IArticleListProps {
	articles: IArticle[];
}

export const ArticleList: React.FC<IArticleListProps> = ({ articles }) => {
	if (articles.length === 0) {
		return (
			<section className="border-t border-gray-200 pt-6" data-testid="article-list-empty" aria-label="Article List">
				<p className="text-sm text-gray-400 italic font-serif">No articles yet — check back soon.</p>
			</section>
		);
	}

	return (
		<section className="flex flex-col border-t border-gray-200" data-testid="article-list" aria-label="Article List">
			{articles.map((article, index) => (
				<ArticleListItem key={article.id} article={article} index={index} />
			))}
			<Footer />
		</section>
	);
};

// frontends/svelte/src/lib/components/article/ArticleList.svelte
<script lang="ts">
	import Footer from '$lib/components//Footer.svelte';
	import ArticleListItem from '$lib/components/article/ArticleListItem.svelte';
	import { type IArticle } from '$lib/types';

	let { articles }: { articles: IArticle[] } = $props();
</script>

{#if articles.length === 0}
	<section class="border-t border-gray-200 pt-6" aria-label="Article List">
		<p class="font-serif text-sm text-gray-400 italic">No articles yet — check back soon.</p>
	</section>
{:else}
	<section class="flex flex-col border-t border-gray-200" aria-label="Article List">
		{#each articles as article, index (article.id)}
			<ArticleListItem {article} {index} />
		{/each}
	</section>
{/if}
<Footer />
