// frontends/svelte/src/lib/components/Footer.svelte
<footer id="footer" class="mt-4 flex flex-row justify-center" aria-label="Footer">
	<a
		href="https://github.com/HarryWillis0"
		target="_blank"
		rel="noopener noreferrer"
		class="icon-button mx-5 text-4xl"
		aria-label="github (opens in new tab)"
	>
		<i class="fa-brands fa-github"></i>
	</a>
	<a
		href="https://www.strava.com/athletes/17003155"
		target="_blank"
		rel="noopener noreferrer"
		class="icon-button mx-5 text-4xl"
		aria-label="strava (opens in new tab)"
	>
		<i class="fab fa-strava"></i>
	</a>
</footer>

// frontends/react/src/components/footer.tsx
import React from "react";

export const Footer: React.FC = () => {
	return (
		<footer id="footer" className="flex flex-row justify-center mt-4">
			<a
				href="https://github.com/HarryWillis0"
				target="_blank"
				rel="noopener noreferrer"
				className="icon-button text-4xl mx-5"
				aria-label="github (opens in new tab)"
			>
				<i className="fa-brands fa-github"></i>
			</a>
			<a
				href="https://www.strava.com/athletes/17003155"
				target="_blank"
				rel="noopener noreferrer"
				className="icon-button text-4xl mx-5"
				aria-label="strava (opens in new tab)"
			>
				<i className="fab fa-strava" />
			</a>
		</footer>
	);
};
